from typing import Protocol

from app.models.domain import (
    Agent,
    AgentRun,
    AgentVersion,
    CronJob,
    Event,
    Gateway,
    Session,
    TopSession,
    UsageDaily,
    UsageSummary,
)


class StorageBackend(Protocol):
    async def init_schema(self) -> None: ...

    async def list_sessions(
        self,
        *,
        active: bool | None = None,
        source: str | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> list[Session]: ...

    async def get_session(self, session_id: str) -> Session | None: ...

    async def upsert_sessions(self, sessions: list[Session]) -> None: ...

    async def list_events(
        self, session_id: str, since: int | None = None, limit: int = 500
    ) -> list[Event]: ...

    async def upsert_events(self, events: list[Event]) -> None: ...

    async def list_cron_jobs(self) -> list[CronJob]: ...

    async def upsert_cron_jobs(self, jobs: list[CronJob]) -> None: ...

    async def list_gateways(self) -> list[Gateway]: ...

    async def upsert_gateways(self, gateways: list[Gateway]) -> None: ...

    async def get_usage_daily(
        self,
        date_from: str | None = None,
        date_to: str | None = None,
        source: str | None = None,
        model: str | None = None,
    ) -> list[UsageDaily]: ...

    async def upsert_usage_daily(self, records: list[UsageDaily]) -> None: ...

    async def get_usage_summary(self) -> UsageSummary: ...

    async def get_usage_by_source(self, limit: int = 10) -> list[dict]: ...

    async def get_usage_by_tool(self, limit: int = 10) -> list[dict]: ...

    async def get_usage_by_model(self, limit: int = 10) -> list[dict]: ...

    async def get_top_sessions(self, limit: int = 10) -> list[TopSession]: ...

    async def get_sync_state(self, key: str) -> str | None: ...

    # --- V2: Agent Registry ---
    async def list_agents(self, *, runtime: str | None = None, scope: str | None = None, q: str | None = None) -> list[Agent]: ...
    async def get_agent(self, agent_id: str) -> Agent | None: ...
    async def create_agent(self, agent: Agent) -> None: ...
    async def update_agent(self, agent: Agent) -> None: ...
    async def delete_agent(self, agent_id: str) -> None: ...
    async def list_agent_versions(self, agent_id: str) -> list[AgentVersion]: ...
    async def get_agent_version(self, agent_id: str, version: int) -> AgentVersion | None: ...
    async def create_agent_version(self, v: AgentVersion) -> None: ...
    async def list_agent_runs(self, agent_id: str, limit: int = 20) -> list[AgentRun]: ...
    async def create_agent_run(self, run: AgentRun) -> None: ...
    async def increment_agent_usage(self, agent_id: str) -> None: ...
    async def list_agents_catalog(self, *, sort: str = "recent", limit: int = 50) -> list[Agent]: ...
    async def get_child_agents(self, parent_agent_id: str) -> list[Agent]: ...

    async def set_sync_state(self, key: str, value: str) -> None: ...
